config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
    get 'home/about'
    get 'home/prices'
    get 'home/search'
    post '/home/search' => 'home/search'
    root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit,:update,:destroy]

  # GET /cryptos
  # GET /cryptos.json
  def index
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'
      
    @url = 'https://api.coinmarketcap.com/v1/ticker/?limit=500'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @my_cryptos = JSON.parse(@response)
  end

  # GET /cryptos/1
  # GET /cryptos/1.json
  def show
      @cryptos = Crypto.all
    require 'net/http'
    require 'json'
      
    @url = 'https://api.coinmarketcap.com/v1/ticker/?limit=500'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @show_cryptos = JSON.parse(@response)
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos
  # POST /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: 'Crypto was successfully created.' }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1
  # PATCH/PUT /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: 'Crypto was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1
  # DELETE /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: 'Crypto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :amount_owned, :paid_per)
    end
    
    def correct_user
       @correct = current_user.cryptos.find_by(id: params[:id])
       redirect_to cryptos_path, notice: "Not Autorized to edit this entry" if @correct.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
          
      
  end
  
  def prices
      require 'net/http'
      require 'json'
      
      @url = 'https://api.coinmarketcap.com/v1/ticker/?limit=500'
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @all_coins = JSON.parse(@response) 
  end
  
  def search
      require 'net/http'
      require 'json'
      
      @url = 'https://api.coinmarketcap.com/v1/ticker/?limit=500'
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @searched_coins = JSON.parse(@response)
      
      @symbol = params[:sym]
      
      # Add some simple error feedback
      
      if @symbol 
          @symbol = @symbol.upcase
      end
      
      if @symbol == ""
          @symbol = "Did you forget to add a currency?"
      end    
  end
  
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<%= form_with(model: crypto, local: true) do |form| %>
  <% if crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
      <% crypto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, value:current_user.id, type: "hidden" %>
  </div>

  <div class="field">
    <%= form.label :amount_owned %>
    <%= form.text_field :amount_owned %>
  </div>

  <div class="field">
    <%= form.label :paid_per %>
    <%= form.text_field :paid_per %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<% profit_loss = 0 %>

<p id="notice"><%= notice %></p>

<h1>My Portfolio</h1>

<br/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Current Price</th>
      <th>7 Day % </th>
      <th>24 Hour % </th>
      <th>1 Hour % </th>
      <th>Owned</th>
      <th>Price Paid Per</th>
      <th>Holdings Value</th>
      <th>Profit/Loss</th>
    </tr>
  </thead>

  <tbody>
    <% @cryptos.each do |crypto| %>    
      <% if crypto.user_id == current_user.id %>
        <% if crypto.symbol %>
            <% crypto.symbol = crypto.symbol.upcase %>
        <% end %>
        <tr>
        <% for x in @my_cryptos %>
            <% if crypto.symbol == x["symbol"] %>
                <td><%= link_to x["rank"], crypto %></td>
                <td><%= link_to x["name"], crypto %></td>
                <td><%= number_to_currency(x["price_usd"]) %></td>
                <% if x["percent_change_7d"].to_i > 0 %>
                    <td class="success"><%= x["percent_change_7d"] %> % </td>
                <% else %>
                    <td class="danger"><%= x["percent_change_7d"] %> % </td>
                <% end %>
                <% if x["percent_change_24h"].to_i > 0 %>
                    <td class="success"><%= x["percent_change_24h"] %> % </td>
                <% else %>
                    <td class="danger"><%= x["percent_change_24h"] %> % </td>
                <% end %>
                <% if x["percent_change_1h"].to_i > 0 %>
                    <td class="success"><%= x["percent_change_1h"] %> % </td>
                <% else %>
                    <td class="danger"><%= x["percent_change_1h"] %> % </td>
                <% end %>
                <td><%= crypto.amount_owned %></td>
                <td><%= number_to_currency(crypto.paid_per) %></td>
                <td><%= number_to_currency(x["price_usd"].to_d * crypto.amount_owned) %></td>
                
                <% if ((x["price_usd"].to_d * crypto.amount_owned) - (crypto.paid_per * crypto.amount_owned)) > 0 %>
                    <td class="success"><%= number_to_currency((x["price_usd"].to_d * crypto.amount_owned) - (crypto.paid_per * crypto.amount_owned)) %></td>
                <% else %>
                    <td class="danger"><%= number_to_currency((x["price_usd"].to_d * crypto.amount_owned) - (crypto.paid_per * crypto.amount_owned)) %></td>
                <% end %>
                <% profit_loss += (x["price_usd"].to_d * crypto.amount_owned - crypto.paid_per * crypto.amount_owned) %>
            <% end %>   
        <% end %>
        </tr>
      <% end %>  
    <% end %>
  </tbody>
</table>

<br/>

<strong>Portfolio Profit/Loss: </strong> <%= number_to_currency(profit_loss) %>

<br/>
<br/>

<%= link_to 'Add Crypto', new_crypto_path, class:"btn btn-primary"%>

app/views/cryptos/new.html.erb
<h1>New Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Back', cryptos_path %>

app/views/cryptos/show.html.erb
<p id="notice"><%= notice %></p>

<% for x in @show_cryptos %>
    <% if @crypto.symbol.upcase == x["symbol"] %>
        <% @crypto_name = x["name"] %>
        <% @crypto_symbol = x["symbol"] %>
        <% @crypto_rank = x["rank"] %>
        <% @crypto_price = x["price_usd"] %>
        <% @crypto_marketcap = x["market_cap_usd"] %>
        <% @crypto_supply = x["available_supply"] %>
        <% @crypto_total = x["total_supply"] %>
        <% @crypto_7d = x["percent_change_7d"] %>
        <% @crypto_24h = x["percent_change_24h"] %>
        <% @crypto_1h = x["percent_change_1h"] %>
    <% end %>
<% end %>    

<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title"><%= @crypto_symbol%> Details</h1>
  </div>
  <div class="panel-body">
    
    <h1><strong><%= @crypto_name %></strong></h1>
    <p><strong>Amount owned: </strong><%= @crypto.amount_owned %></p>
    <p><strong>Paid per: </strong><%= @crypto.paid_per %></p>
    <p><strong>Current Price: </strong><%= number_to_currency(@crypto_price) %></p>
    <p><strong>Market Cap: </strong><%= number_to_currency(@crypto_marketcap) %></p>
    <p><strong>Available: </strong><%= number_to_currency(@crypto_supply) %></p>
    <p><strong>Total Supply: </strong><%= number_to_currency(@crypto_total) %></p>
    
  </div>
  
  <div class="panel-footer">
    <button type="button" class="btn btn-default"><%= link_to 'Edit', edit_crypto_path(@crypto) %></button>
    <button type="button" class="btn btn-default"><%= link_to 'Delete', crypto_path(@crypto), method: :delete, data: {confirm: 'Are you sure?'} %></button>
    <button type="button" class="btn btn-default"><%= link_to 'Back', cryptos_path %></button>
  </div>
</div>

app/views/home/_flash.html.erb
 
<% flash.each do |name,msg| %>
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_navbar.html.erb
 


<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "Dashboard", root_path, class: "navbar-brand" %></li>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Prices", home_prices_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to "Portfolio", cryptos_path %></li>
        <% end %>
        <li><%= link_to "Search", home_search_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", home_about_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to "Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>    
            <li><%= link_to "Register", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
 
<h1>About</h1>
<p>Cryptocurrency monitoring dashboard using the Coinmarketcap API V1.</p>

app/views/home/dummy.html.erb
 
<h1>Test Page</h1>
<p>Try to get things working properly.</p>

<% @test_coins %>

<% for x in @test_coins %>
    <% for coin in @my_test %>
        <% if coin == x["symbol"] %>
            <%= x["name"] %>: <%= x["price_usd"] %></br></br>
        <% end %>
    <% end %>    
<% end %>

app/views/home/index.html.erb
<h1>Dashboard</h1>
<p>Welcome to your dashboard.</p>



<% if user_signed_in? %>
    "You are signed in"
<% else %>
    "Want to sign in or register?"
<% end %>

app/views/home/prices.html.erb
<h1>Cryptocurrency Prices</h1>
<p>All the latest market updates.</p>

<br/>
<br/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>  
      <th>Name</th>
      <th>Current Price</th>
      <th>Market Cap</th>
      <th>7 Day % </th>
      <th>24 Hour % </th>
      <th>1 Hour % </th>
    </tr>
  </thead>

  <tbody>
    <% @all_coins.each do |coin| %>
        <tr>
            <td><%= coin["rank"] %><br/></td>
            <td><%= coin["name"] %><br/></td>
            <td><%= number_to_currency(coin["price_usd"]) %><br/></td>
            <td><%= number_to_currency(coin["market_cap_usd"]) %></td>
            <% if coin["percent_change_7d"].to_i > 0 %>
                    <td class="success"><%= coin["percent_change_7d"] %> % </td>
                <% else %>
                    <td class="danger"><%= coin["percent_change_7d"] %> % </td>
                <% end %>
                <% if coin["percent_change_24h"].to_i > 0 %>
                    <td class="success"><%= coin["percent_change_24h"] %> % </td>
                <% else %>
                    <td class="danger"><%= coin["percent_change_24h"] %> % </td>
                <% end %>
                <% if coin["percent_change_1h"].to_i > 0 %>
                    <td class="success"><%= coin["percent_change_1h"] %> % </td>
                <% else %>
                    <td class="danger"><%= coin["percent_change_1h"] %> % </td>
                <% end %>
        </tr>
    <% end %>
  </tbody>
</table>  

app/views/home/search.html.erb
<h3>Search</h3>
<p>Get details ion a single currency.</p>
 
<br/>
 
<%= form_tag home_search_path, :method => 'POST' do %>
   <%= text_field_tag 'sym', nil, placeholder: 'Enter the symbol of your currency', size: 50 %>
   <%= submit_tag 'Seach for currency' %>
<% end %>
 
<br/>

<% if @symbol %> 
    <% for x in @searched_coins %>
        <% if @symbol == x["symbol"] %>
            <%= x["name"] %>: <%= x["price_usd"] %></br></br>
        <% end %>    
    <% end %>
<% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  
    <%= render 'home/navbar' %>
  
    <div class="container">
        <%= render 'home/flash' %>
        <%= yield %>
    </div>
  
    
  </body>
</html>